remove italic from "sp."
Artsdatabanken/assessments-frontend pull request #1327
Opened 2023-08-22 11:47 UTC by matssa

Fixes #535

2023-08-22 13:18 UTC, helemork commented on Assessments.Frontend.Web/Views/AlienSpecies/2023/AlienSpeciesIndex.cshtml
> -                    @*<img src="https://design.artsdatabanken.no/list-icons/FA.png" alt="Bilde av en mandarinand" />*@
Men... vil vi ikke HA bildet av en mandarinand? Høres jo flott ut!

2023-08-22 13:27 UTC, helemork approved these changes

2023-08-22 13:33 UTC, helemork requested changes
![bilde](https://github.com/Artsdatabanken/assessments-frontend/assets/17450081/e76b5d20-ae00-4958-8d10-a2b854e229a0)

2023-08-23 08:36 UTC, matssa commented on Assessments.Frontend.Web/Views/AlienSpecies/2023/AlienSpeciesIndex.cshtml
> -                    @*<img src="https://design.artsdatabanken.no/list-icons/FA.png" alt="Bilde av en mandarinand" />*@
Nei, den er for 2018 og ikke fremmedartslista generelt.

2023-08-23 10:21 UTC, helemork commented on Assessments.Mapping/AlienSpecies/Helpers/AlienSpeciesAssessment2023ProfileHelper.cs
> +            if (src.EvaluatedScientificName == "Onchocleidus sp.")
Really?
Dette er ikke måten å fikse det på.
Dette må fikses i kildedataene. Vi kan ikke lage unntak for enkelte takson.

2023-08-23 11:28 UTC, merged