Feature/species groups statistics
Artsdatabanken/assessments-frontend pull request #1373
Opened 2023-12-12 14:01 UTC by matssa

Gjør om virkemåten for filter på rødlista for arter til å fungere likt som for fremmedartslista. 

Fixes #264 for filtre med flere enn 4 valg, slik som for fremmedartslista.
Forberedelse til #1369 
Her har jeg testa at filter fungerer likt som det gjør i produksjon i dag, men det er fint om flere enn meg tester dette.

2024-01-02 12:54 UTC, AneMarlene requested changes
Tjohei - det blir bra med en "merk alle" på Rødlistefilteret også👍 👍
Jeg satte på meg granske-brillene og fant sannelig noe her og der som må fikses før den kan gå på lufta. Jeg har for øvrig ikke sett på "Forberedelse til https://github.com/Artsdatabanken/assessments-frontend/issues/1369", ettersom jeg regner med reviewen på det kommer når figuren er på plass(?!) :) 

I tillegg til de øvrige kommentarene som er filter-spesifikke, så ser jeg på et overordnet nivå at filtertelleren har blitt feil. Den teller nå med "merk alle" som et (reelt) filter. Jeg tror du har en fiks på det inne i fremmedartskoden et sted (da vi hadde samme issue der en gang)? 

![image](https://github.com/Artsdatabanken/assessments-frontend/assets/58254444/50346e42-58cd-4790-8d4b-65a4f03af413)

2024-01-02 12:54 UTC, AneMarlene commented on Assessments.Frontend.Web/Infrastructure/RedlistSpecies/Enums/RedlistSpeciesAssessment2021Habitats.cs
> +        Våtmarkssystemer,
Her har det lurt seg inn en liten "f" (på l. 38) Hvis jeg skrur på "merk alle" lokalt, og merker av alle (på den manuelle tungvinte måten..) i prod, så blir utvalget forskjellig i prod (11 720) og lokalt (11 376). Dette skyldes i alle fall delvis at man får null treff på Semi-naturlig mark lokalt (pga. nevnte feil i verdi vil jeg tro). Men dette skal utgjøre 2308 arter, så det forklarer antagelig ikke hele forskjellen ettersom 11 376 + 2308 != 11 720... kanskje du ser noe mer?

Jeg lurer også på om ikke hovedhabitat ligger som en enum på datamodellen til Rødlista? Om det gjør det, så hadde det kanskje vært bedre å bruke den direkte, gitt at dette ikke er et subset av en større enum? (du trenger ikke svare ut dette altså - det er bare åpne spørsmål som du får vurdere..) :)

2024-01-16 09:48 UTC, matssa commented on Assessments.Frontend.Web/Infrastructure/RedlistSpecies/Enums/RedlistSpeciesAssessment2021Category.cs
> +        END,
Har reparert litt her nå :) Skal funke bedre enn prod!

2024-01-16 10:50 UTC, matssa commented
Da er feilene over utbedret.

2024-01-17 14:23 UTC, AneMarlene approved these changes
Nu snakker vi ⭐ ⭐ ⭐ ⭐ ⭐

2024-01-17 14:24 UTC, merged