Mapping/diverse felt - stort sett relatert til forekomstareal
Artsdatabanken/assessments-frontend pull request #730
Opened 2022-11-21 10:25 UTC by AneMarlene

Diverse felt lagt til på datamodellen, noen også i eksporten. De fleste er relatert til forekomstareal (AOO). Closes #729. 

- lagt til alle felt som handler om forekomstareal for både selvstendig reproduserende arter (nåtid og framtid) og dørstokkarter (framtid). Sørger for at de kun viser fram innhold for riktig type art (dette bestemmes ved hjelp av AssessmentConclusion).
- lagt til hjelpefunksjoner for å regne ut verdien på felt som ikke lå lagret på datamodellen i FAB. Dette gjelder lavt og høyt anslag på antall introduksjoner for dørstokkarter, samt forekomstareal (lavt, beste og høyt anslag) etter 10 år for dørstokkartene. Disse hjelpefunksjonene er hentet direkte fra https://github.com/Artsdatabanken/Fremmedartsbase2023/blob/main/Prod.Api/Helpers/ExportMapper.cs 
- lagt til funksjon som sørger for at vi ikke viser fram arealer som er større enn tilgjengelig areal for den gitte arten (se issue #729).

2022-11-21 11:56 UTC, matssa requested changes
Fint å få inn masse data til modellen! 😄 
Jeg ber om noen endringer når det gjelder lesbarhet på nøstede kondisjoner. De er vanskelige å lese. 
Kunne også ha tenkt meg de forslagene til forbedringer jeg har lagt inn på enklere kode.

Til sist så lurer jeg på hvorfor det er brukt long og ulong i masse funksjoner her. Hadde det ikke vært tilstrekkelig med int? Jeg mener man generelt ikke bør gå opp i størrelse på typen med mindre man har behov for det, eller at det finnes en mulighet for at behovet oppstår i fremtiden. [nummertyper i c#](https://learn.microsoft.com/en-us/dotnet/csharp/language-reference/builtin-types/integral-numeric-types)

2022-11-21 11:56 UTC, matssa commented on Assessments.Mapping/AlienSpecies/Helpers/AlienSpeciesAssessment2023ProfileHelper.cs
> +                        : (long)(4 * Math.Round(occ + Math.Pow(intr, ((double)occ + 9) / 10)));
Generelt så synes jeg koden blir lettere å lese dersom man bruker if/else når det begynner å komme nøstede kondisjoner.

2022-11-21 11:56 UTC, matssa commented on Assessments.Mapping/AlienSpecies/Helpers/AlienSpeciesAssessment2023ProfileHelper.cs
> +                : IntroductionsLow(ra);
Dette synes jeg blir bortimot uleselig. Kan lese det, men da må jeg konsentrere meg hardt...

2022-11-21 11:56 UTC, matssa commented on Assessments.Mapping/AlienSpecies/Helpers/AlienSpeciesAssessment2023ProfileHelper.cs
> +            return null;
Her kan du gjøre slik jeg har gjort i GetEnvironmentEnum i AlienSpeciesAssessment2023ProfileHelper.cs.
```
var value = 0;
            if (limnic)
                value += 1;
            if (marine)
                value += 2;
            if (terrestrial)
                value += 4;

            return value switch
            {
                1 => AlienSpeciesAssessment2023Environment.Limnisk,
                2 => AlienSpeciesAssessment2023Environment.Marint,
                3 => AlienSpeciesAssessment2023Environment.LimMar,
                4 => AlienSpeciesAssessment2023Environment.Terrestrisk,
                5 => AlienSpeciesAssessment2023Environment.LimTer,
                6 => AlienSpeciesAssessment2023Environment.MarTer,
                7 => AlienSpeciesAssessment2023Environment.LimMarTer,
                _ => AlienSpeciesAssessment2023Environment.Unknown
            };
```
Ikke sikkert du kan bruke lambda switch slik jeg har gjort, men du kan se på switches for å få den til å funke: [switch](https://learn.microsoft.com/en-us/dotnet/csharp/language-reference/statements/selection-statements#the-switch-statement)

2022-11-21 12:13 UTC, AneMarlene commented on Assessments.Mapping/AlienSpecies/Helpers/AlienSpeciesAssessment2023ProfileHelper.cs
> +                : IntroductionsLow(ra);
hehe, jeg kunne ikke vært mer enig :D ...fikk av en eller annen grunn ikke til å bruke if/else her, for da ignorerte den resultatet - selv om jeg først plasserte variablen utenfor if/else.. Hjelp meg gjerne til å få dette til å se bedre ut eller forstå hvordan en if/else kan implenteres her.

2022-11-21 18:59 UTC, AneMarlene commented on Assessments.Mapping/AlienSpecies/Helpers/AlienSpeciesAssessment2023ProfileHelper.cs
> +                : IntroductionsLow(ra);
Fixed :)

2022-11-21 19:15 UTC, AneMarlene commented on Assessments.Mapping/AlienSpecies/Helpers/AlienSpeciesAssessment2023ProfileHelper.cs
> +                        : (long)(4 * Math.Round(occ + Math.Pow(intr, ((double)occ + 9) / 10)));
enig og har endret.

2022-11-22 14:18 UTC, AneMarlene commented on Assessments.Mapping/AlienSpecies/Helpers/AlienSpeciesAssessment2023ProfileHelper.cs
> +            return null;
juhu - det var lurt! Et forsøk er pushet - men dette er "min" [les: forsynte meg rått av forslaget ditt] første switch, så her er det sikkert forbedringspotensial ;)

2022-11-23 08:56 UTC, matssa commented on Assessments.Mapping/AlienSpecies/Helpers/AlienSpeciesAssessment2023ProfileHelper.cs
> +            return null;
Switchen din ser bra ut. 😃 
Det er bare en ting jeg har å utsette på den. Det er bruken av magiske strenger. [Her](https://softwareengineering.stackexchange.com/questions/365339/what-is-wrong-with-magic-strings) kan du lese det første svaret som forklarer godt hvorfor man bør unngå det. AssessmentConclusion er kanskje ikke en enum, så du får ikke brukt det på den måten, men å definere strengene som variabler over switchen bør funke ok i dette tilfellet. Altså `var norway = "N";` og `var assessedSelvReproducing = "AssessedSelfReproducing";` 
Ikke aktuelt her, men greit å være klar over at det samme gjelder for magiske tall. Magi er sjelden noe særlig i koding...

Ellers, default case: kunne dette vært 0, eller er 0 en aktuell verdi som kan brukes ellers? Det hadde vært fint å fått denne til en int i stedet for int?, men skjønner om det ikke går.

2022-11-23 15:00 UTC, matssa approved these changes
Good stuff :)

2022-11-23 15:00 UTC, merged