Feature/expert summary
Artsdatabanken/assessments-frontend pull request #731
Opened 2022-11-21 11:14 UTC by matssa

Legger inn ekspertvurderinger - Fixes #713 
Se #728 på kommende navneendring. Dette må nesten implementeres når den endringen er inne. 

Begynt å legge viewModel inn i model-mappa i stedet for å overbelaste stakkars AlienSpeciesDetailView-fila :)

2022-11-22 10:29 UTC, AneMarlene requested changes
Gleder meg til å fylle alle vurderingene med tekst. <3  Det er dog noen endringer som må gjøres for å få det helt riktig. De endringene som gjelder NR-arter tar jeg på meg skylda for ettersom jeg skrev spørringen feil i issuet =) 

Jeg har også slengt på noen (bedre?) forslag til forklaring for en del av objektene ;)

2022-11-22 10:29 UTC, AneMarlene commented on Assessments.Mapping/AlienSpecies/Model/AlienSpeciesAssessment2023.cs
> +        /// </summary>
Uncertainty around the establishment category. Free text field.

2022-11-22 10:29 UTC, AneMarlene commented on Assessments.Mapping/AlienSpecies/Model/AlienSpeciesAssessment2023.cs
> +        /// </summary>
Short conclusion/summary of the impact assessment. Free text field

2022-11-22 10:29 UTC, AneMarlene commented on Assessments.Mapping/AlienSpecies/Model/AlienSpeciesAssessment2023.cs
> +        /// </summary>
Description and documentation of the species' ecological effects. Free text field

2022-11-22 10:29 UTC, AneMarlene commented on Assessments.Mapping/AlienSpecies/Model/AlienSpeciesAssessment2023.cs
> +        /// </summary>
Description of the species' distribution in Norway. Free text field

2022-11-22 10:29 UTC, AneMarlene commented on Assessments.Mapping/AlienSpecies/Model/AlienSpeciesAssessment2023.cs
> +        /// </summary>
Description and documentation of the species' invasion potential. Free text field

2022-11-22 10:29 UTC, AneMarlene commented on Assessments.Mapping/AlienSpecies/Model/AlienSpeciesAssessment2023.cs
> +        /// </summary>
Description of relevant aspects of taxonomy, the species life history and ecology. Free text field

2022-11-22 10:29 UTC, AneMarlene commented on Assessments.Mapping/AlienSpecies/Model/AlienSpeciesAssessment2023.cs
> +        /// </summary>
The short reason why an earlier believed alien species is no longer considered alien (or null)

2022-11-23 07:31 UTC, matssa commented on Assessments.Frontend.Web/Views/AlienSpecies/2023/AssessmentPartials/_ExpertStatement.cshtml
> +
Ja, det ble litt komplisert dette. Men nå blir det forhåpentligvis ordnet opp i.

2022-11-23 07:38 UTC, matssa commented on Assessments.Frontend.Web/Views/AlienSpecies/2023/AssessmentPartials/_ExpertStatement.cshtml
> +                        @Html.Raw(Model.CriteriaDocumentationSpeciesStatus)
Godt poeng. Dette ser jo litt kantete ut.

2022-11-23 07:54 UTC, matssa commented on Assessments.Mapping/AlienSpecies/Helpers/AlienSpeciesAssessment2023ProfileHelper.cs
> +        }
Hehe, ja dette hadde jeg ikke gjettet 😆

2022-11-23 08:06 UTC, matssa commented on Assessments.Mapping/AlienSpecies/Model/Enums/AlienSpeciesAssessment2023ChangedFromAlien.cs
> +    }
Den er grei:)

2022-11-23 08:09 UTC, matssa commented on Assessments.Frontend.Web/Views/AlienSpecies/2023/AssessmentPartials/_ExpertStatement.cshtml
> +                !string.IsNullOrEmpty(Model.SpreadFurtherSpreadFurtherInfo);
Joda, alle disse ligger inni en div som sjekker om categori ikke er NR eller om AlienSpeciesCategory ikke er TaxonEvaluatedAtAnotherLevel

2022-11-23 08:18 UTC, matssa commented on Assessments.Frontend.Web/Views/AlienSpecies/2023/AssessmentPartials/_ExpertStatement.cshtml
> +                Model.AlienSpeciesCategory != Assessments.Mapping.AlienSpecies.Model.Enums.AlienSpeciecAssessment2023AlienSpeciesCategory.TaxonEvaluatedAtAnotherLevel;
Du har helt rett! Skal fikse

2022-11-23 08:19 UTC, matssa commented on Assessments.Frontend.Web/Views/AlienSpecies/2023/AssessmentPartials/_ExpertStatement.cshtml
> +                Model.AlienSpeciesCategory == Assessments.Mapping.AlienSpecies.Model.Enums.AlienSpeciecAssessment2023AlienSpeciesCategory.TaxonEvaluatedAtAnotherLevel;
😸

2022-11-23 08:24 UTC, matssa commented on Assessments.Mapping/AlienSpecies/Model/AlienSpeciesAssessment2023.cs
> +        public string ChangedAssessment { get; set; }
Skal endre beskrivelse samt navn.

2022-11-23 08:26 UTC, matssa commented on Assessments.Mapping/AlienSpecies/Model/AlienSpeciesAssessment2023.cs
> +        public string ConnectedToHigherLowerTaxonDescription { get; set; }
jepp jepp jepp

2022-11-23 08:28 UTC, matssa commented on Assessments.Mapping/AlienSpecies/Model/AlienSpeciesAssessment2023.cs
> +        /// </summary>
:)

2022-11-23 08:29 UTC, matssa commented on Assessments.Mapping/AlienSpecies/Model/AlienSpeciesAssessment2023.cs
> +        /// </summary>
Synes forklaringen min passet godt til navnet dens, men dette er kanskje en bedre forklaring ja...

2022-11-23 08:30 UTC, matssa commented on Assessments.Mapping/AlienSpecies/Model/AlienSpeciesAssessment2023.cs
> +        /// </summary>
:)

2022-11-23 08:31 UTC, matssa commented on Assessments.Mapping/AlienSpecies/Model/AlienSpeciesAssessment2023.cs
> +        /// </summary>
:)

2022-11-23 08:31 UTC, matssa commented on Assessments.Mapping/AlienSpecies/Model/AlienSpeciesAssessment2023.cs
> +        /// </summary>
:)

2022-11-23 08:31 UTC, matssa commented on Assessments.Mapping/AlienSpecies/Model/AlienSpeciesAssessment2023.cs
> +        /// </summary>
:)

2022-11-23 08:32 UTC, matssa commented on Assessments.Mapping/AlienSpecies/Model/AlienSpeciesAssessment2023.cs
> +        /// </summary>
:)

2022-11-23 08:32 UTC, matssa commented on Assessments.Mapping/AlienSpecies/Model/AlienSpeciesAssessment2023.cs
> +        /// </summary>
:)

2022-11-23 08:32 UTC, matssa commented on Assessments.Mapping/AlienSpecies/Model/AlienSpeciesAssessment2023.cs
> +        /// </summary>
:)

2022-11-23 08:33 UTC, matssa commented on Assessments.Mapping/AlienSpecies/Model/AlienSpeciesAssessment2023.cs
> +        /// </summary>
:)

2022-11-23 08:33 UTC, matssa commented on Assessments.Mapping/AlienSpecies/Model/AlienSpeciesAssessment2023.cs
> +        /// </summary>
:)

2022-11-23 11:22 UTC, AneMarlene commented on Assessments.Mapping/AlienSpecies/Helpers/AlienSpeciesAssessment2023ProfileHelper.cs
> +        }
nå ble den nydelig og funker som den skal :)

2022-11-23 11:27 UTC, AneMarlene approved these changes

2022-11-23 11:32 UTC, merged