Filters: category change, ecological effect, invation potential
Artsdatabanken/assessments-frontend pull request #733
Opened 2022-11-21 16:17 UTC by matssa

Legger inn den faktiske dataen til filteret for endring i risikokategori. Fixes #696 
Legger til filter for økologisk effekt,
Legger til filter for invasjonspotensial Fixes #631

2022-11-25 19:47 UTC, AneMarlene requested changes
Dette blir bra :) Jeg har et par kommentarer som jeg håper det er mulig å ordne. Den aller viktigste er rimelig enkel (tror jeg da) og er den som kan spores tilbake til meg selv, ellers virker alt å fungere som det skal. :)

2022-11-25 19:47 UTC, AneMarlene commented on Assessments.Frontend.Web/Infrastructure/AlienSpecies/FilterHelpers.cs
> +                    return String.Empty;
Disse to skulle ligge under filtertemaet Risikokategori, da disse skårene avgjør kategori :)  Det er også mer intuitivt med invasjonspotensial først, og økologisk effekt etterpå (x-aksen før y-aksen mao): 

![image](https://user-images.githubusercontent.com/58254444/204043668-6fd241a2-4d90-43e2-966a-c55fd36dc027.png)

2022-11-25 19:47 UTC, AneMarlene commented on Assessments.Frontend.Web/Infrastructure/AlienSpecies/FilterHelpers.cs
>              count += parameters.CategoryChanged.Length;
Nå skriver jeg sikkert kommentaren på feil linje i koden, men la merke til at dette filter-temaet ikke kommer med en slik snasen telling på hvor mange brukte filtre det er under dette temaet (slik som vist for bruksart under): 

<img width="161" alt="image" src="https://user-images.githubusercontent.com/58254444/204045356-4f7a14ca-3f43-4a84-89eb-512f1ba8e538.png">

2022-11-28 07:45 UTC, matssa commented on Assessments.Frontend.Web/Infrastructure/AlienSpecies/QueryHelpers.cs
Ikke noe problem :)

2022-11-28 07:50 UTC, matssa commented on Assessments.Frontend.Web/Infrastructure/AlienSpecies/QueryHelpers.cs
> +                    nameof(CategoryChangeEnum.ccvf) => query.Where(x => x.PreviousAssessments.Count == 0 || x.PreviousAssessments.Any(y => y.RevisionYear == 2018 && y.Category == AlienSpeciesAssessme
Det gir jo veldig mening at "vurdert for første gang" faktisk må være vurdert også ja... 😄

2022-11-28 09:23 UTC, matssa commented on Assessments.Frontend.Web/Infrastructure/AlienSpecies/FilterHelpers.cs
> +                    return String.Empty;
Fikk flytta dem, men du må se på bruken av disse. De vil nå få en annen virkning enn de hadde tidligere.

2022-11-28 09:27 UTC, matssa commented on Assessments.Frontend.Web/Infrastructure/AlienSpecies/FilterHelpers.cs
>              count += parameters.CategoryChanged.Length;
Oi, godt funnet! 🍨

2022-12-01 13:07 UTC, AneMarlene commented on Assessments.Frontend.Web/Infrastructure/AlienSpecies/QueryHelpers.cs
takk :)

2022-12-01 13:23 UTC, AneMarlene commented on Assessments.Frontend.Web/Infrastructure/AlienSpecies/FilterHelpers.cs
> +                    return String.Empty;
Da har jeg sett på bruken - og skjønner hva du mener. Det er funksjonen vi hadde tidligere vi ønsker oss, så vi flytter de ut igjen. To ting når de flyttes ut: 
1. navn på filtrene endres fra _Invasjonspotensial_ til _Invasjonspotensial (risikomatrisens x-akse)_ og fra _Økologisk effekt_ til _Økologisk effekt (risikomatrisens y-akse)_
2. Se om det er mulig å få inn hjelpetekstene for hver av de (se skjermdumpen over)

2022-12-01 13:24 UTC, AneMarlene commented on Assessments.Frontend.Web/Infrastructure/AlienSpecies/FilterHelpers.cs
>              count += parameters.CategoryChanged.Length;
og godt fikset :)

2022-12-02 09:16 UTC, matssa commented on Assessments.Frontend.Web/Infrastructure/AlienSpecies/FilterHelpers.cs
> +                    return String.Empty;
Flyttet filterne og endret navn på dem. 
Lagd en egen issue for hjelpetekster https://github.com/Artsdatabanken/assessments-frontend/issues/741

2022-12-02 09:24 UTC, merged