Feature/map svalbard
Artsdatabanken/assessments-frontend pull request #829
Opened 2023-01-10 14:31 UTC by matssa

Fixes #801 
Viser kun frem Svalbard-kartet når en vurdering gjelder for Svalbard. 
Denne må merges inn etter #822 da den bygger på den.

2023-01-10 15:23 UTC, helemork requested changes
Flere ting her:
- [ ] Legende + bilde må samsvare
- [ ] Ikke putt legende og tittel i samme, det gir ikke mening
- [ ] er vi sikker på at svalbard skal kodes som tre kart, for jeg har ennå ikke fått opp mer enn et kart etter å ha bladd igjennom mange kart. Så noe er tydelig feil en plass
- [ ] Se øvrige forslag i andre kommentarer

2023-01-10 15:27 UTC, helemork commented
Dette gjelder både norges- og svalbard-kart:

Legende er ikke samsvarende med tittel.
Fargebruk bør ikke samsvare med tidshorisont, men betydningen av et felt (aka kjent/antatt/ikke-antatt).
Det er ikke hjelpsomt for leseren at hvert kart har sin egen farge, tvert om er det vanskeligere å sammenligne. 
Så gi heller dataen en tydelig betydning!

![bilde](https://user-images.githubusercontent.com/17450081/211591605-f0970710-ea5d-4033-a4a6-a0e1852ba63e.png)
![bilde](https://user-images.githubusercontent.com/17450081/211592205-ddf0c586-5d10-4f86-a97a-bf67db48b93b.png)

2023-01-11 07:53 UTC, matssa commented on Assessments.Frontend.Web/Views/AlienSpecies/2023/AssessmentPartials/_RegionalSpread.cshtml
> +                        <div is-visible="Model.IsSvalbard" class="map triple_map">
Nei, da ble kartene kjempesmå.

2023-01-11 08:57 UTC, matssa commented
Har lagd en egen issue på legende/tabell #834

2023-01-11 08:57 UTC, merged