Naturtypetilhørighet
Artsdatabanken/assessments-frontend pull request #843
Opened 2023-01-11 12:56 UTC by helemork

fixes #817 - Naturtypetilhørighet 
- Lagt til forhåpentligvis alt som ble bedt om i dokumentet.
- Laget et mobil-tabelloppsett for mobil som kobles på ved 750px (samme som på andre ting, gjenbrukte only-mobile)
- Laget table-description css klasse som matcher tabelltypen den tilhører.
- Justerte kontraster og slikt for normal + darktheme.

Men, css'en er meget uoversiktlig nå. 
Det burde vært splittet mer opp.
Jeg har ikke oversikt over hvorfor filene nå er som de er :|

2023-01-11 14:45 UTC, AneMarlene commented on Assessments.Frontend.Web/Views/AlienSpecies/2023/AssessmentPartials/_ImpactedNatureTypes.cshtml
> +                    <th>vurderingsgrunnlag</th>
Dette er noget detaljert, men brytningen på "tydelig tilstandsendring" ble litt suboptimal. Innholdet i denne kolonna tar også en del plass. Jeg foreslår derfor at vi lager den kolonna litt bredere på bekostning av kolonna før (kolonisert areal (%)). Innholdet i den kolonna tar nemlig mindre plass, og ordet "areal" kan kanskje "hoppe ned" og stå sammen med "(%)". 

![image](https://user-images.githubusercontent.com/58254444/211835667-4b8cad17-f1ab-475f-912a-7976c6d7868e.png)

2023-01-11 14:49 UTC, AneMarlene requested changes
Dette ble veldig pent. Jeg tar selvkritikk på noen suboptimale setninger som de andre i biologiteamet kan ta en titt på, ellers ser det svært så pent ut. Jeg har kun én kommentar (se egen kommentar over) som jeg håper vi får fiksa før den aksepteres.

2023-01-11 15:22 UTC, matssa reviewed
Lar det bli opp til @AneMarlene å approve denne, men koden ser grei ut (bortsett fra formateringa med feil indentering og masse unødvendige tomme linjer). 😄

2023-01-11 15:22 UTC, matssa commented on Assessments.Frontend.Web/Views/AlienSpecies/2023/AssessmentPartials/_ImpactedNatureTypes.cshtml
> +                        <td><b class="only_mobile">naturtype:</b>@natureType.Name</td>
Får litt fnatt av den formateringa her 😱

2023-01-12 11:14 UTC, AneMarlene approved these changes
Nydelig :)

2023-01-12 11:14 UTC, merged