Risikoforklaring for F og G-kriteriet
Artsdatabanken/assessments-frontend pull request #912
Opened 2023-01-25 16:20 UTC by matssa

Fixes #902 

Legger til 
- ThreatenedNatureTypesAffectedDomesticDescription
- CommonNatureTypesAffectedDomesticDescription
fra RiskAssessment og legger til et felt i lista ImpactedNatureTypes
- IsThreatened

2023-01-26 09:51 UTC, AneMarlene commented on Assessments.Frontend.Web/Views/AlienSpecies/2023/AssessmentPartials/_RiskCategoryExplanation.cshtml
> +                                            </div>
Mulig jeg ikke har vært presis nok i bestillingen her :D 
Det virker ikke som at GetFGTable tar hensyn til at den kun skal vise de naturtypene med IsThreatned == true på F-kriteriet (og kun de naturtypene med IsThreatned ==false på G-kriteriet). Mulig showFTable må brukes på en annen måte, jeg vet ikke :) F.eks. på Abies concolor skal kun 1 av naturtypene vises i tabellen på F-kriteriet (det er den som oppfyllet kravet til showFTable, altså naturtypen Kalk- og lågurtfuruskog).

2023-01-26 09:55 UTC, AneMarlene commented on Assessments.Frontend.Web/Views/AlienSpecies/2023/AssessmentPartials/_RiskCategoryExplanation.cshtml
> +                                                }
Samme kommentar som over. Her er en eksempelart Sambucus racemosa, hvor kun tre av naturtypene skal listes opp (de som oppfyller showGTable).

2023-01-26 09:58 UTC, AneMarlene requested changes
Åh, denne var så _nesten_ i mål og blir veldig bra! 👍  ..men må nesten få sett det endelige resultatet før den merges, så jeg requester en endring. :----D [Se kommentarene under]

2023-01-30 09:30 UTC, matssa commented on Assessments.Frontend.Web/Views/AlienSpecies/2023/AssessmentPartials/_RiskCategoryExplanation.cshtml
> +                                            </div>
Aha, jeg må ha lest litt for fort på issuet. Trodde det var forutsetningen for om tabellen skulle vises, ikke for hver linje i tabellen. Da lager jeg en sjekk for hver linje i tillegg :)

2023-01-31 17:55 UTC, matssa commented
Peker denne pull requesten mot "layout" i stedet, da den hadde skapt masse ekstra konfliktløsing for layout-branchen dersom denne gikk til master. Den eneste praktiske forskjellen er at vi også må merge layout før denne vises på test.

2023-02-02 10:15 UTC, AneMarlene submitted a review, later dismissed
Nå ser det helt riktig ut og jeg er lykkelig :D Godt jobba!

2023-02-02 10:37 UTC, merged